version: '3'

services:
    web:
        build: .
        depends_on:
            - db
        links:
            - db
        env_file: ./instagram_own_version/dev.env
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 127.0.0.1:8000:8000
    db:
        image: postgres:14
        env_file:
            - ./instagram_own_version/dev.env
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
