# Generated by Django 3.2.11 on 2022-02-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dislike",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="like",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
