# Generated by Django 3.2.11 on 2022-02-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0004_auto_20220223_1106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.DeleteModel(
            name="Dislike",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
