name: Linters

on: [push]

env:
  POETRY_VERSION: 1.0.3
  WORK_DIR: .


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run pylama
        run: |
          poetry run pylama

      - name: Run black
        run: |
          poetry run pylama black .
