name: Tests

on: [push]

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: instagram_project
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install Dependencies
      run: |
        poetry install
        poetry shell

    - name: Run Tests
      run: |
        python manage.py test

      env:
        CORE_DB_DATABASE: instagram_project
        CORE_DB_USERNAME: admin
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: instagram_project
